#!/usr/bin/env bash

SCRIPT_PATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )" || exit 1
cd "$SCRIPT_PATH" || exit 1

git pull origin master

go run cmd/main.go Alan-prog/wireguard_vpn master