#!/usr/bin/env bash

SCRIPT_PATH="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )" || exit
cd "$SCRIPT_PATH" || exit
git pull origin master
go run cmd/process_git_trigger.go Alan-prog/wireguard_vpn slave &
